// Github/global_test.go
//
// Test values used throughout the package.

package Github

import (
	"os"
	"testing"
)

// ============================================================================
// Variables
// ============================================================================

var TestClient *Client

// ============================================================================
// Internal variables - samples
// ============================================================================

var sampleUser *User
var sampleRepo *Repository

// ============================================================================
// Functions - samples
// ============================================================================

// An existing user object acquired from GitHub.
func SampleUser(client *Client) *User {
    if sampleUser == nil {
        if client == nil {
            client = TestClient
        }
        sampleUser = client.GetUser(SAMPLE_USER)
    }
    return sampleUser
}

// An existing repository object acquired from GitHub.
func SampleRepository(client *Client) *Repository {
    if sampleRepo == nil {
        if client == nil {
            client = TestClient
        }
        sampleRepo = client.GetRepository(SAMPLE_ORG, SAMPLE_REPO)
    }
    return sampleRepo
}

// ============================================================================
// Functions - fakes
// ============================================================================

// Prevent cleanup of temporary GitHub items generated by test execution.
func PreserveFakes() {
    postCleanFakes = false
}

// Force cleanup of all detected temporary GitHub items.
func CleanUpAll() {
    postCleanAll = true
}

// ============================================================================
// Test setup
// ============================================================================

// Invoked once by "go test" for any/all tests in this package.
func TestMain(m *testing.M) {
    testSetup()
    code := m.Run()
    testTeardown()
    os.Exit(code)
}

// Setup functions run before tests begin.
func testSetup() {
    testSetup_Client()
    testSetup_User()
    testSetup_Repository()
    testSetup_Issue()
    testSetup_Comment()
}

// Teardown functions run after tests finish.
func testTeardown() {
    testTeardown_Comment()
    testTeardown_Issue()
    testTeardown_Repository()
    testTeardown_User()
    testTeardown_Client()
}
